[package]
name = "dicey-sys"
version = "0.3.9"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.69.4"
cmake = "0.1.50"
pkg-config = "0.3.30"

[features]
static = []
